### ISSUE TITLE
Contribute in some features in this project

### ISSUE THREAD

**Issue by niktekusho** [gakimball/prepend-cwd#1]
Hi, I'm using this little module (why to reinvent the wheel when there's something already done and with tests? 😄 ) in one of my projects, and I was thinking if you were interested in receiving a few PRs (by me):

* [x] Update Travis CI environment config to:
     *   remove node version 7
     *   add node version 8 (currently maintained LTS)
     *   add node version 10 (currently maintained and node major LTS)
     *   add tests on macOs (Windows builds on Travis CI are **very** unstable as of today)
* [x] Upgrade dependencies:
     *   As of today, both mocha and xo are detected as insecure when `npm install`ing. The screenshot below as proof. This "security issue" is not a problem since they are development dependencies but, since I think this should be easily fixable, I would gladly make it right.
* [x] Create a TypeScript definition file (*.d.ts) to allow devs to have a more refined autocomplete in most IDEs (VS Code, Atom, etc.)

Since those changes are by no means breaking the public API of the module, I think the eventual release could be a minor or patch release (a patch release should be favorable since it should be downloaded in most cases by npm or yarn without forcing changes to existing `package.json` files).

**Comment by niktekusho** [comment]
I forgot the screenshot...

![image](https://user-images.githubusercontent.com/18280135/51753652-9fe37280-20ba-11e9-87cc-901ad0e88c3b.png)

**Comment by gakimball** [comment]
Merged #2, thank you!

**Comment by niktekusho** [comment]
> Merged #2, thank you!

The others will be right back...

**Comment by gakimball** [comment]
Published 2.0.0 👌 Thanks again for the contributions!
